### ISSUE TITLE
[DG] Overall Formatting 

### ISSUE THREAD

**Issue by kerct** [AY2223S2-CS2113-T13-3/tp#103]
- Please finish up the sections that are not completed 
- Double check the structure (non-functional requirements is repeated twice)
- Missing instructions for manual testing
- The scope of the diagrams is good, however please provide an explanation instead of just putting the diagrams there
- Inconsistencies (e.g. for bullet points, full stop or no full stop at the end? capital or no capital for the first letter?)
- I believe it should be "saveGoal" in the screenshot below
<img width="430" alt="image" src="https://user-images.githubusercontent.com/12395454/228747968-78e3b2b6-6c2a-41a4-9f42-6d0ac5377dd4.png">

- Similarly, please use the name accurately for this
<img width="203" alt="image" src="https://user-images.githubusercontent.com/12395454/228748259-28eacc05-8da0-4bfd-afd0-dabb12157545.png">

It is important to ensure that the DG is accurate, so a thorough check is required!

**Comment by xiaoge26** [comment]
Thank you for your feedback! It is really helpful. We will improve the guide!
