### ISSUE TITLE
[PE-D][Tester A] [Bug] Printing error when user enter '0' balance in the phase of the account creation.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-3/tp#112]
If I enter `0$` balance in the phase of the account creation, my balance is indicated as `00$` with the double zero. Refer the image below:

<img src="https://raw.githubusercontent.com/0nandon/ped/main/files/b7c9fd39-6b1a-4e8f-a725-ac1b7cdbba8e.png" width=400>

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: 0nandon/ped#2

**Comment by vishnuvk47** [comment]
Noted as per issue #97 and will fix soon, Thanks! 

P.s: have covered this under latest pull request so can close issue once PR #109  merged

**Comment by vishnuvk47** [comment]
closed after merging PR #109
