### ISSUE TITLE
[PE-D][Tester B] I cannot switch my account.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-3/tp#113]
![image.png](https://raw.githubusercontent.com/L0Z1K/ped/main/files/3abdd817-0fce-441f-8287-18c2c28c48a6.png)

I execute command, `switch-to yoon` but nothing happens.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: L0Z1K/ped#2

**Comment by vishnuvk47** [comment]
have been marked under #63, will fix soon!

**Comment by vishnuvk47** [comment]
solved under PR #109
