### ISSUE TITLE
[PE-D][Tester B] Showing balance is a bit strange.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-3/tp#126]
![image.png](https://raw.githubusercontent.com/L0Z1K/ped/main/files/4bf68eed-9b75-40d5-902d-712e70432fe2.png)

I think it should show balance like $0. not $00

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: L0Z1K/ped#7

**Comment by vishnuvk47** [comment]
can close once #109 is merged
