### ISSUE TITLE
[PE-D][Tester C] invalid command still taken in as valid

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-3/tp#131]
![image.png](https://raw.githubusercontent.com/SaiChaitanya13/ped/main/files/b6af05e7-c463-4433-bca4-6b2557810a23.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: SaiChaitanya13/ped#2

**Comment by vishnuvk47** [comment]
<img width="981" alt="Screenshot 2023-04-01 at 1 26 47 PM" src="https://user-images.githubusercontent.com/122626659/229267313-761f45e7-b044-4569-ab47-8c95bdcbda08.png">
<img width="1053" alt="Screenshot 2023-04-01 at 1 30 00 PM" src="https://user-images.githubusercontent.com/122626659/229267440-d4f4a5ae-b5eb-434c-903b-c2b253a7a0a9.png">

Mentioned in UG that extraneous parameters will be ignored, Though the add-account wasn't mentioned in the "such as" portion--meant to be non-exhaustive, it was mentioned in the add-account subsection that it doesn't take any parameters. Nevertheless, will resolve this by changing this portion of UG to include all commands that will not care about extraneous commands, Thanks for the heads up.
