### ISSUE TITLE
[PE-D][Tester C] Doesn't seem to delete the account.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T13-3/tp#133]
![image.png](https://raw.githubusercontent.com/SaiChaitanya13/ped/main/files/568b62e5-ab9f-4e67-93a9-319942e04c0b.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: SaiChaitanya13/ped#4

**Comment by vishnuvk47** [comment]
can close once PR #109 is merged.
