### ISSUE TITLE
[PE-D][Tester A] [Bug] Save command is not working.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T13-3/tp#142]
It seems that save command is not working. Refer the image below:

<img src="https://raw.githubusercontent.com/0nandon/ped/main/files/072e8ff0-98b8-4d7a-9aea-1cc4d49d6fdc.png" width=400>

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: 0nandon/ped#11

**Comment by vishnuvk47** [comment]
The name save was rather misleading for the task of adding a save goal and the command was changed last min; hence, UG wasn't updated. Thanks for the spot will look to update the UG accordingly.

**Comment by vishnuvk47** [comment]
Change already made in the latest UG
