### ISSUE TITLE
Handle leading zero exception

### ISSUE THREAD

**Issue by xiaoge26** [AY2223S2-CS2113-T13-3/tp#68]
I found this bug while testing the program. We should ban leading zeros.

`How much would you like to add as Balance?
090
----------------------------
Account created!
Name: xixi
Balance: $090
----------------------------
Found 1 Account
`

**Comment by vishnuvk47** [comment]
have solved this in PR #75 as well

**Comment by vishnuvk47** [comment]
made a small edit to change the code that removes leading zeroes to be placed after the .trim().

can close this issue once PR #76 is merged
